### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/NamedTuples.jl#63]
Could someone make me a co-maintainer of this package? I'd like to help out. In reality I have done that over the last two years in any case (if you look at the contribution page), and secondly my suite of packages is probably one of the larger users of this package, so I'd like to help make sure we don't break things.

Not sure whom to ping, so I'll just try the usual suspects: @quinnj, @nalimilan, @ararslan.

**Comment by quinnj** [comment]
Added!

**Comment by davidanthoff** [comment]
Great, thanks!
